name: Playwright Tests (API e Web)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  api-tests:
    name: API Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      # Security audit como aviso + relatório JSON
      - name: Security audit (npm) — JSON report
        continue-on-error: true
        run: |
          npm audit --audit-level=moderate --json > audit-report.json || echo "npm audit returned non-zero"
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report-api
          path: audit-report.json
          retention-days: 30

      - name: Install Playwright (API only needs deps for request, but install browsers for parity)
        run: npx playwright install --with-deps
      - name: Run Playwright API tests
        run: npx playwright test --project=api
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-api
          path: playwright-report/
          retention-days: 30

  web-tests:
    name: Web Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      # Security audit como aviso + relatório JSON
      - name: Security audit (npm) — JSON report
        continue-on-error: true
        run: |
          npm audit --audit-level=moderate --json > audit-report.json || echo "npm audit returned non-zero"
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report-web
          path: audit-report.json
          retention-days: 30

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Web tests
        run: npx playwright test --project=chromium --project=firefox --project=webkit
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-web
          path: playwright-report/
          retention-days: 30
